### ISSUE TITLE
Allow Custom SVG Icons for Infobox

### ISSUE THREAD

**Issue by shazahm1** [kadencethemes/kadence-blocks#30]
Please add a filter(s) to allow custom SVG icons to be added or allow SVG files to be used as icons from the Media Library.

I know I can already upload SVG icons into the Media Library but then the options for Icons Size and Color are not available.

**Comment by kadencethemes** [comment]
Hey,
Thanks for posting.

 A filter is tricky because the bundled icons are broken down to data like this:

`FaIco['fa_image'] = {'vB':'0 0 512 512', 'cD':[{'nE':'path','aBs':{'d':'M464 64H48C21.49 64 0 85.49 0 112v288c0 26.51 21.49 48 48 48h416c26.51 0 48-21.49 48-48V112c0-26.51-21.49-48-48-48zm-6 336H54a6 6 0 0 1-6-6V118a6 6 0 0 1 6-6h404a6 6 0 0 1 6 6v276a6 6 0 0 1-6 6zM128 152c-22.091 0-40 17.909-40 40s17.909 40 40 40 40-17.909 40-40-17.909-40-40-40zM96 352h320v-80l-87.515-87.515c-4.686-4.686-12.284-4.686-16.971 0L192 304l-39.515-39.515c-4.686-4.686-12.284-4.686-16.971 0L96 304v48z'}}]};`

Then put together when the icon is selected.

There would need to be a number of filters and it would require outputting some generators to create that broken down data. For now, I am going to table that.

 Instead, I added some basic improved support for adding SVGs from the media library. Meaning the max width will now have an effect so you can effectively change the size. 

Then I also added a color field which shows if the image is an SVG. That color field won't give you a live preview but can have an effect on the frontend if you are using the https://wordpress.org/plugins/svg-support/ plugin and have turned on force inline svg or are using the class "kt-info-svg-image".

This will all be part of the next update.

**Comment by kadencethemes** [comment]
I've pushed that update out, let me know if you have any issues.

Ben

**Comment by shazahm1** [comment]
Thanks, seems to work great.
